spring.application.name=micacharrito

# Conexion a la base de datos: en Render llega por variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Mantiene tus datos iniciales y estructura
spring.jpa.hibernate.ddl-auto=update

# El puerto lo asigna Render automaticamente
server.port=${PORT:8080}

# Origenes CORS dinamicos (clave para tu clase ConfiguracionCors)
app.cors.origins=${CORS_URL:http://localhost:4200}
